<script lang="ts">
	import Sidebar from '$lib/components/Sidebar.svelte';
	let isSuccess = $state(false);
</script>

<svelte:head>
	<title>Reveal Transaction – Umbra Treasury</title>
</svelte:head>

<div class="flex h-screen overflow-hidden bg-[#09090b]">
	<Sidebar />

	<div class="flex-1 md:ml-64 flex flex-col min-h-screen">
		<header class="bg-[#09090b] border-b border-[#27272a] flex justify-between items-center w-full px-6 h-16 sticky top-0 z-40">
			<div class="flex items-center gap-4">
				<a href="/dashboard" class="text-zinc-400 hover:text-zinc-100 hover:bg-[#18181b] transition-colors p-1.5 rounded-lg">
					<span class="material-symbols-outlined">arrow_back</span>
				</a>
				<h1 class="font-h3 text-h3 text-white">Reveal Transaction</h1>
			</div>
		</header>

		<main class="flex-1 overflow-y-auto p-6 flex items-center justify-center relative">
			<!-- Background Glow for success state -->
			{#if isSuccess}
				<div class="absolute inset-0 z-0 overflow-hidden pointer-events-none">
					<div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-[#10b981]/5 rounded-full blur-[100px]"></div>
				</div>
			{/if}

			<div class="w-full max-w-lg z-10">
				{#if !isSuccess}
					<!-- Input Modal -->
					<div class="bg-[#18181b] border border-[#27272a] rounded-xl overflow-hidden shadow-2xl">
						<div class="p-6 border-b border-[#27272a] bg-[#1e1f26]/50 flex justify-between items-center">
							<div class="flex items-center gap-3">
								<div class="w-10 h-10 rounded-lg bg-zinc-800 border border-zinc-700 flex items-center justify-center">
									<span class="material-symbols-outlined text-zinc-400">key</span>
								</div>
								<div>
									<h2 class="font-h3 text-h3 text-white leading-none">Decrypt Payload</h2>
									<p class="text-[12px] text-zinc-400 font-medium mt-1">No transaction selected yet</p>
								</div>
							</div>
						</div>

						<div class="p-8 space-y-6">
							<p class="font-body-md text-body-md text-zinc-400">
								This transaction is encrypted. Please provide the viewing key generated by the DAO or sender to reveal the payload details.
							</p>

							<div class="flex flex-col gap-2">
								<label class="font-label-mono text-label-mono text-zinc-500 uppercase tracking-widest" for="viewing_key">Viewing Key</label>
								<input
									id="viewing_key"
									type="password"
									placeholder="vk1_..."
									class="bg-[#0d0e15] border border-[#27272a] focus:border-[#10b981] focus:ring-1 focus:ring-[#10b981] rounded-lg px-4 py-3 font-mono text-sm text-white placeholder:text-zinc-700 transition-all"
								/>
							</div>

							<div class="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-3 flex gap-3">
								<span class="material-symbols-outlined text-yellow-500 text-sm mt-0.5" style="font-variation-settings: 'FILL' 1;">warning</span>
								<p class="text-xs text-yellow-500/90 leading-tight">
									Decrypted data will only be visible locally in your browser. It is never re-broadcast to the network.
								</p>
							</div>

							<div class="flex gap-3 pt-2">
								<button class="px-6 py-3 border border-[#27272a] rounded-lg font-bold text-xs text-zinc-300 hover:bg-[#27272a] transition-colors uppercase tracking-widest">
									Cancel
								</button>
								<button
									onclick={() => isSuccess = true}
									class="flex-1 bg-white text-black font-bold py-3 rounded-lg text-xs uppercase tracking-widest hover:bg-zinc-200 transition-colors active:scale-[0.99] flex items-center justify-center gap-2"
								>
									<span class="material-symbols-outlined text-[16px]">lock_open</span>
									Decrypt Transaction
								</button>
							</div>
						</div>
					</div>
				{:else}
					<!-- Success Modal -->
					<div class="bg-[#18181b] border border-[#10b981]/50 rounded-xl overflow-hidden shadow-[0_0_40px_-10px_rgba(16,185,129,0.2)]">
						<div class="p-6 border-b border-[#27272a] bg-[#1e1f26]/50 flex justify-between items-center">
							<div class="flex items-center gap-3">
								<div class="w-10 h-10 rounded-lg bg-[#10b981]/10 border border-[#10b981]/20 flex items-center justify-center">
									<span class="material-symbols-outlined text-[#10b981] font-bold" style="font-variation-settings: 'FILL' 1;">visibility</span>
								</div>
								<div>
									<h2 class="font-h3 text-h3 text-white leading-none">Transaction Revealed</h2>
									<p class="text-[12px] text-[#10b981] font-medium mt-1">Decryption Successful</p>
								</div>
							</div>
						</div>

						<div class="p-8 space-y-8">
							<div class="text-center">
								<span class="text-zinc-500 font-label-mono text-label-mono uppercase">Amount revealed</span>
								<h3 class="text-[42px] font-black text-[#10b981] tracking-tight mt-2">No data yet</h3>
							</div>

							<div class="grid grid-cols-1 gap-px bg-[#27272a] border border-[#27272a] rounded-lg overflow-hidden">
								<div class="bg-[#0d0e15] p-4 flex justify-between items-center">
									<span class="text-zinc-500 text-xs font-medium">Recipient Address</span>
									<div class="flex items-center gap-2">
										<span class="font-mono text-xs text-white">No data yet</span>
										<button class="material-symbols-outlined text-[16px] text-zinc-500 hover:text-white">content_copy</button>
									</div>
								</div>
								<div class="bg-[#0d0e15] p-4 flex justify-between items-center">
									<span class="text-zinc-500 text-xs font-medium">Execution Date</span>
									<span class="text-xs text-white">No data yet</span>
								</div>
								<div class="bg-[#0d0e15] p-4 flex justify-between items-center">
									<span class="text-zinc-500 text-xs font-medium">Category</span>
									<div class="flex items-center gap-2 px-2 py-1 rounded bg-[#10b981]/10 border border-[#10b981]/20">
										<span class="w-1.5 h-1.5 rounded-full bg-[#10b981]"></span>
										<span class="text-[10px] font-bold text-[#10b981] uppercase tracking-wider">No data yet</span>
									</div>
								</div>
								<div class="bg-[#0d0e15] p-4 flex justify-between items-center">
									<span class="text-zinc-500 text-xs font-medium">Privacy Status</span>
									<div class="flex items-center gap-1.5 text-[#10b981]">
										<span class="material-symbols-outlined text-[16px]" style="font-variation-settings: 'FILL' 1;">verified</span>
										<span class="text-xs font-bold">No data yet</span>
									</div>
								</div>
							</div>

							<button
								onclick={() => isSuccess = false}
								class="w-full bg-[#10b981] text-[#002113] font-black py-4 rounded-lg text-sm tracking-wide transition-all hover:bg-[#4edea3] active:scale-[0.99] flex items-center justify-center gap-2"
							>
								Done
							</button>
						</div>

						<div class="px-8 py-4 bg-[#0d0e15] border-t border-[#27272a] flex items-center justify-center gap-6">
							<div class="flex items-center gap-2">
								<span class="material-symbols-outlined text-[14px] text-zinc-600">security</span>
								<span class="text-[10px] text-zinc-600 font-mono">ENCRYPTION: AES-256-GCM</span>
							</div>
						</div>
					</div>
				{/if}
			</div>
		</main>
	</div>
</div>
